### ISSUE TITLE
ProductStream fails in volume filter. Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by emilmork** [rexxars/vinmonopolet#7]
ProductStream fails when calling .match on val (This happens after receiving ~10-50 products every time)

The `val` is probably not a String and not an empty String.

[Suggested solution: return null if val is falsy](https://github.com/rexxars/vinmonopolet/pull/6)

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'match' of undefined
```

**Comment by rexxars** [comment]
Solved in #6
